name: Review Dependencies

on:
  pull_request:
    branches:
      - main

# Cancel any runs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-review:
    uses: nodejs/web-team/.github/workflows/dependency-review.yml
