on:
  push:
    branches:
      - main

name: Notify on Push
permissions:
  contents: read

jobs:
  notify_on_push:
    name: Notify on any direct push to `main`
    if: >
      github.repository == 'nodejs/nodejs.org' &&
      github.actor != 'github-merge-queue[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: nodejs/web-team/actions/notify-on-push@4fe2167f55e4aa670f7f97da16490945bb061d51
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
