# Security Notes
# Only selected Actions are allowed within this repository. Please refer to (https://github.com/nodejs/nodejs.org/settings/actions)
# for the full list of available actions. If you want to add a new one, please reach out a maintainer with Admin permissions.
# REVIEWERS, please always double-check security practices before merging a PR that contains Workflow changes!!
# AUTHORS, please only use actions with explicit SHA references, and avoid using `@master` or `@main` references or `@version` tags.

name: Playwright Tests on Cloudflare Open-Next

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  playwright:
    name: Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - uses: nodejs/web-team/actions/setup-environment@4fe2167f55e4aa670f7f97da16490945bb061d51
        with:
          pnpm: true
          fetch-depth: 2
          use-version-file: true

      - name: Get Playwright version
        id: playwright-version
        working-directory: apps/site
        run: echo "version=$(node_modules/.bin/playwright --version | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}

      - name: Install Playwright Browsers
        working-directory: apps/site
        run: node_modules/.bin/playwright install --with-deps

      - name: Run Playwright tests
        working-directory: apps/site
        run: node --run playwright
        env:
          PLAYWRIGHT_RUN_CLOUDFLARE_PREVIEW: true
          PLAYWRIGHT_BASE_URL: http://127.0.0.1:8787

      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: playwright-report
          path: apps/site/playwright-report/
